"""post and comments schema updates

Revision ID: 15d6f2ce77c8
Revises: d4b2f1a9c0ef
Create Date: 2026-03-10 11:33:45.452899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d6f2ce77c8'
down_revision: Union[str, Sequence[str], None] = 'd4b2f1a9c0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('races', sa.Column('external_provider', sa.String(), nullable=True))
    op.add_column('races', sa.Column('last_synceft_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uix_internal_race', 'races', ['external_id', 'external_provider'])
    op.create_unique_constraint(None, 'races', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'races', type_='unique')
    op.drop_constraint('uix_internal_race', 'races', type_='unique')
    op.drop_column('races', 'last_synceft_at')
    op.drop_column('races', 'external_provider')
    op.drop_column('races', 'external_id')
    # ### end Alembic commands ###
