"""implemented club operations

Revision ID: 8866fc8eaa6e
Revises: 55b1cd36dda2
Create Date: 2026-02-28 17:07:35.025980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8866fc8eaa6e'
down_revision: Union[str, Sequence[str], None] = '55b1cd36dda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'is_deleted')
    # ### end Alembic commands ###
