"""added event invitation table

Revision ID: 8d993d5db7ad
Revises: 933b3d5f4713
Create Date: 2026-02-28 17:27:56.393071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d993d5db7ad'
down_revision: Union[str, Sequence[str], None] = '933b3d5f4713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_deleted')
    # ### end Alembic commands ###
