"""worked on the route model

Revision ID: ccd1924a94dc
Revises: 8d993d5db7ad
Create Date: 2026-03-06 02:32:32.791374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd1924a94dc'
down_revision: Union[str, Sequence[str], None] = '8d993d5db7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('start_address', sa.String(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=False),
    sa.Column('end_lng', sa.Float(), nullable=False),
    sa.Column('end_address', sa.String(), nullable=True),
    sa.Column('map_data', sa.String(), nullable=False),
    sa.Column('avoid_pollution', sa.Boolean(), nullable=True),
    sa.Column('environment', sa.Enum('max_shade', 'open_air', name='environmentenum'), nullable=True),
    sa.Column('terrain', sa.Enum('paved', 'unpaved', name='terrainenum'), nullable=True),
    sa.Column('elevation_profile', sa.Enum('flat', 'hilly', name='elevationprofileenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_foreign_key(None, 'events', 'routes', ['route_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'runs', 'routes', ['route_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
